### ISSUE TITLE
修改建议

### ISSUE THREAD

**Issue by diy4869** [cliclitv/vue-clicli#10]
> 首页
1. 首页搜索可以显眼一点
2. 右上角的编辑感觉色调过于强烈
3. 登录接口挂掉了 502
4. 建议番剧、电影分开
5. 番剧这种可以加个筛选功能

> 番剧详情
1. 番剧图片可以小一点
2. 视频信息建议放上面，不用翻到底部才能看到
3. 制作信息可以放到侧边，会好点

**Comment by yisar** [comment]
番剧有筛选

番剧详情，暂时不改

其他的，今天搞定
