### ISSUE TITLE
下次重构记录

### ISSUE THREAD

**Issue by yisar** [cliclitv/vue-clicli#11]
1. 预留广告位
2. 【buy me a coffee】
3. 换域名

**Comment by dxhuii** [comment]
又准备换啥域名，后缀都注册完了吧。广告位不错，要有良性发展。

**Comment by yisar** [comment]
> 又准备换啥域名

clicli.tv

**Comment by dxhuii** [comment]
> > 又准备换啥域名
> 
> clicli.tv

那不是要出血了，.tv 的还是很贵的。 目前发现 https://www.namesilo.com/ 这里最便宜。

**Comment by yisar** [comment]
已经买了::>_<::1k，唉

**Comment by dxhuii** [comment]
从别人手里面买的啊。奢侈、
