### ISSUE TITLE
c站 寒假重构计划

### ISSUE THREAD

**Issue by yisar** [cliclitv/vue-clicli#2]
### 区块链

全面使用区块链技术重构，包括 ipfs、货币交易、非对称加密、eos等
每次经济危机都意味着新技术的崛起，08年互联网崛起了，2019年互联网寒冬了
这意味，又是一场革命

而，人工智能，区块链，深度学习，神经网络等新技术是逆袭的可能

我觉得我作为前端，区块链是以上唯一可以驾驭的
这也是 c站 唯一彻底从技术层面与 b站 区分开的机会

所以，寒假重构，区块链是最关键的

### 小程序

现在这个时间点，小程序原生支持了组件化、模块化，编译型框架已经不需要了
我是时候去掺一腿了，争取这次能够发一个小程序框架（配合 smox）

### acgzone
会重写 acgzone，作为 clicli 专栏的存在，使用我最近开源的 框架 fre 来重写

## 寒假前要做的

1. 使用 web-components 重构 eplayer，从技术层面，超越 b站 的 dplayer
2. 重构 smox，着重是研究 patch-updating 和 immed

以上，近期 c站 重构计划，重构，不会因为我一次次的失利而停止

**Comment by jwchan1996** [comment]
追随大佬的脚步:pig:

**Comment by yisar** [comment]
告一段落，eplayer 和 smox 重构完成，c站 重构重开 issue
