### ISSUE TITLE
Error: Cannot find module '../dist/vue-ssr-client-manifest.json'

### ISSUE THREAD

**Issue by drduan** [cliclitv/vue-clicli#7]
D:\vue-clicli>cnpm start

> vue-idanmu@1.0.0 start D:\vue-clicli
> node server/app.js

internal/modules/cjs/loader.js:615
    throw err;
    ^

Error: Cannot find module '../dist/vue-ssr-client-manifest.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:613:15)
    at Function.Module._load (internal/modules/cjs/loader.js:539:25)
    at Module.require (internal/modules/cjs/loader.js:667:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (D:\vue-clicli\server\ssr-online.js:16:24)
    at Module._compile (internal/modules/cjs/loader.js:738:30)`
`

**Comment by yisar** [comment]
需要 yarn build 完，再 yarn start
开发环境直接 yarn dev

**Comment by drduan** [comment]
啊 npm cnpm 不可以吗

**Comment by drduan** [comment]
![image](https://user-images.githubusercontent.com/7875572/54880857-a9a01100-4e84-11e9-9f50-cfc475a8173f.png)
使用yarn start

**Comment by yisar** [comment]
啊，jx 这个没有传上来，你找到这句删了吧，不影响

**Comment by drduan** [comment]
哈哈 你改天还是提一下吧

**Comment by drduan** [comment]
![image](https://user-images.githubusercontent.com/7875572/54880997-3f886b80-4e86-11e9-8f78-8e0355185c20.png)
Error: Cannot find module './api/bit'

**Comment by yisar** [comment]
这些模块都删掉吧，都是解析模块，不开源的::>_<::

>哈哈 你改天还是提一下吧

不能提啊，这个模块是直链解析模块，宝藏，sorry

**Comment by drduan** [comment]
![image](https://user-images.githubusercontent.com/7875572/54881063-c9d0cf80-4e86-11e9-8b89-3e2c717ec1eb.png)
ok都注释掉了 漂亮 明天学习

**Comment by yisar** [comment]
很好很好，那我关掉 issue 啦
